version: "3.8"

services:
  # OCR Editing Application
  ocr-editing:
    build:
      context: .
      dockerfile: Dockerfile
    image: ocr-editing:latest
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env.local
    environment:
      NODE_ENV: production
    volumes:
      # Mount upload directory (create if not exists)
      - ./public/uploads:/app/public/uploads
      # Mount logs directory  
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || curl -f http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Socket.IO Realtime Gateway
  realtime:
    image: node:23-slim
    working_dir: /app
    command: ["node", "realtime/server.cjs"]
    ports:
      - "${WS_PORT:-4000}:4000"
    env_file:
      - .env.local
    environment:
      NODE_ENV: production
      WS_PORT: 4000
    volumes:
      - ./:/app

  # Development version - Commented out for now
  # ocr-editing-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: ocr-editing:dev
  #   restart: unless-stopped
  #   ports:
  #     - "3001:3000"  # Dev runs on port 3001
  #   env_file:
  #     - .env.local
  #   environment:
  #     NODE_ENV: development
  #     PORT: 3000  # Internal port
  #   volumes:
  #     # Mount upload directory
  #     - ./public/uploads:/app/public/uploads
  #     # Mount logs
  #     - ./logs:/app/logs
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || curl -f http://localhost:3000/ || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 40s
  #   # Lower resource limits for dev
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 512M
  #         cpus: '0.5'
  #       reservations:
  #         memory: 256M
  #         cpus: '0.25'
