// Video Editor Models - Clean exports for video editor only

// Core User & Auth models
export { User } from "./user";
export { UserRole } from "./user_role";
export { UserSubscription } from "./user_subscription";

// Video Editor entities
export { VideoTask } from "./video_task";
export { Video } from "./video";
export { VideoEditSettings } from "./video_edit_settings";
export { SubtitleTrack } from "./subtitle_track";

// Subscription & Payment models
export { SubscriptionPlan } from "./subscription_plan";
export { Payment } from "./payment";

// Utility models
export { RefreshToken } from "./refresh_token";

// Type definitions for API responses
export interface ApiResponse<T = any> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}

export interface PaginatedResponse<T = any> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
}

// Video Editor specific interfaces
export interface VideoTaskWithVideos {
  videos?: any[];
  primaryVideo?: any;
  subtitleTracks?: any[];
}

export interface VideoUploadData {
  taskId: number;
  sourceUrl?: string;
  file?: File;
  filename?: string;
}

export interface SubtitleGenerationData {
  videoId: number;
  languageCode: string;
  isAutoGenerated: boolean;
}

// Form data interfaces
export interface CreateVideoTaskData {
  title: string;
  description?: string;
}

export interface UpdateVideoTaskData {
  title?: string;
  description?: string;
  status?: "draft" | "processing" | "completed" | "failed";
}
